# Generated by Django 4.0.3 on 2023-09-04 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'managed': False, 'verbose_name': '유저', 'verbose_name_plural': '유저'},
        ),
    ]
